app/__init__.py
from flask import Flask


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'your_secret_key'

    from .views import views
    from .restapi import  restapi
    from .camera import VideoCamera
    app.register_blueprint(views, url_prefix='/')
    restapi.register_blueprint(views, url_prefix='/')

    return app

app/views.py
from flask import Blueprint, render_template, Response
from .camera import VideoCamera, PredictCamera

views = Blueprint('views', __name__)

video_stream = VideoCamera()
prediction_stream = PredictCamera()

@views.route('/', methods=['GET','POST'])
def home():
    return render_template('index.html')

def gen(camera):
    while True:
        frame = camera.get_frame()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

@views.route('/video_feed')
def video_feed():
     return Response(gen(video_stream),
                    mimetype='multipart/x-mixed-replace; boundary=frame')

@views.route("/prediction_feed")
def predict_feed():
    return Response(gen(prediction_stream),
                    mimetype='multipart/x-mixed-replace; boundary=frame')

app/templates/image.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<img src = "static/images/image0.png">
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask Object Detection</title>
</head>
<body class="text-center">
<!--    <img src="{{ url_for('views.video_feed') }}" />-->
    <img src="{{ url_for('views.predict_feed') }}" />
  </body>
</html>